repository:
  name: language-peer
  description: "🗣️ Voice-first GenAI language learning with autonomous AI agents powered by AWS Bedrock and Strands"
  homepage: https://github.com/username/language-peer
  topics: 
    - genai
    - hackathon
    - voice-ui
    - modular-agents
    - aws
    - aws-bedrock
    - language-learning
    - ai-agents
    - strands
    - typescript
    - serverless
    - transcribe
    - polly
    - comprehend
    - voice-first
    - conversation-ai
    - aws-cdk
    - react
    - nodejs
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: aws
    color: FF9900
    description: Related to AWS services
  - name: bedrock
    color: purple
    description: AWS Bedrock related
  - name: voice-processing
    color: orange
    description: Voice/audio processing related
  - name: agents
    color: green
    description: AI agent related