blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/asharanees/language-peer/tree/main/docs
    about: Check our comprehensive documentation first
  - name: 💬 Discussions
    url: https://github.com/asharanees/language-peer/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🚀 AWS GenAI Hackathon
    url: https://aws.amazon.com/
    about: Learn more about the AWS GenAI Hackathon